# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
service:
  url: http://localhost:8091
spring:
  jpa:
    show-sql: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: user
    password:

server:
  port: 8090
