# Docker configuration
service:
  url: http://host.docker.internal:8091
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/orderservice
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234

server:
  port: 8090
